version: "3.3"

networks:
  web:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK}

services:

  php-5.6:
    restart: always
    build: ./images/php-5.6
    container_name: php-5.6
    hostname: php-5.6
    ports:
      - 9000
    volumes:
      - ${WORKPLACE_PWD}:/var/www
      - ./etc/php/php-5.6.ini:/usr/local/etc/php/php.ini
      - ./etc/php/php-5.6.www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      web:
        ipv4_address: ${NETWORK_PHP_56}
  php-7.0:
    restart: always
    build: ./images/php-7.0
    container_name: php-7.0
    hostname: php-7.0
    ports:
      - 9000
    volumes:
      - ${WORKPLACE_PWD}:/var/www
      - ./etc/php/php-7.0.ini:/usr/local/etc/php/php.ini
      - ./etc/php/php-7.0.www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      web:
        ipv4_address: ${NETWORK_PHP_70}
  php-7.1:
    restart: always
    build: ./images/php-7.1
    container_name: php-7.1
    hostname: php-7.1
    ports:
      - 9000
    volumes:
      - ${WORKPLACE_PWD}:/var/www
      - ./etc/php/php-7.1.ini:/usr/local/etc/php/php.ini
      - ./etc/php/php-7.1.www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      web:
        ipv4_address: ${NETWORK_PHP_71}
  php-7.2:
    restart: always
    build: ./images/php-7.2
    container_name: php-7.2
    hostname: php-7.2
    ports:
      - 9000
    volumes:
      - ${WORKPLACE_PWD}:/var/www
      - ./etc/php/php-7.2.ini:/usr/local/etc/php/php.ini
      - ./etc/php/php-7.2.www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      web:
        ipv4_address: ${NETWORK_PHP_72}
  php-7.3:
    restart: always
    build: ./images/php-7.3
    container_name: php-7.3
    hostname: php-7.3
    ports:
      - 9000
    volumes:
      - ${WORKPLACE_PWD}:/var/www
      - ./etc/php/php-7.3.ini:/usr/local/etc/php/php.ini
      - ./etc/php/php-7.3.www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      web:
        ipv4_address: ${NETWORK_PHP_73}
  php-7.4:
    restart: always
    build: ./images/php-7.4
    container_name: php-7.4
    hostname: php-7.4
    ports:
      - 9000
    volumes:
      - ${WORKPLACE_PWD}:/var/www
      - ./etc/php/php-7.4.ini:/usr/local/etc/php/php.ini
      - ./etc/php/php-7.4.www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      web:
        ipv4_address: ${NETWORK_PHP_74}

  nginx:
    restart: always
    build: ./images/nginx
    container_name: nginx
    hostname: nginx
    ports:
      - 80:80
    volumes:
      - ./etc/nginx:/etc/nginx
      - ./etc/nginx/log:/var/log/nginx
      - ${WORKPLACE_PWD}:/var/www
    networks:
      web:
        ipv4_address: ${NETWORK_NGINX}


  redis:
    restart: always
    build: ./images/redis
    container_name: redis
    hostname: redis
    command: redis-server --requirepass ${REDIS_PWD}
    ports:
      - ${PORT_REDIS}:6379
    volumes:
      - ./etc/redis/data:/data
      - ./etc/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      web:
        ipv4_address: ${NETWORK_REDIS}

  rabbitmq:
    restart: always
    build: ./images/rabbitmq
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PWD}
    ports:
      - ${PORT_RABBITMQ}:5672
      - 1${PORT_RABBITMQ}:15672
    networks:
      web:
        ipv4_address: ${NETWORK_RABBITMQ}

  mysql-master: &mysql-master
    restart: always
    build: ./images/mysql
    container_name: mysql-master
    hostname: mysql-master
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=${MYSQL_MASTER_ROOT_PWD}
    ports:
      - ${PORT_MYSQL_MASTER}:3306
    expose:
      - ${PORT_MYSQL_MASTER}
    volumes:
      - ./etc/mysql/master/data:/var/lib/mysql
      - ./etc/mysql/master/logs:/var/log/mysql
      - ./etc/mysql/master/conf.d:/etc/mysql/conf.d
    command: [
      "--log-bin=mysql-bin",
      "--server-id=${MYSQL_MASTER_SERVER_ID}",
      "--binlog-ignore-db=mysql",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      "--innodb_flush_log_at_trx_commit=1",
      "--default_authentication_plugin=mysql_native_password",
      "--sync_binlog=1",
    ]
    networks:
      web:
        ipv4_address: ${NETWORK_MYSQL_MASTER}
  mysql-slave-1: &mysql-slave-1
    <<: *mysql-master
    restart: always
    build: ./images/mysql
    container_name: mysql-slave-1
    hostname: mysql-slave-1
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=${MYSQL_SLAVE_1_ROOT_PWD}
      - MASTER_MYSQL_ROOT_PASSWORD=${MYSQL_MASTER_ROOT_PWD}
    ports:
      - ${PORT_MYSQL_SLAVE_1}:3306
    depends_on:
      - mysql-master
    volumes:
      - ./etc/mysql/slave_1/data:/var/lib/mysql
      - ./etc/mysql/slave_1/logs:/var/log/mysql
      - ./etc/mysql/slave_1/conf.d:/etc/mysql/conf.d
    command: [
      "--server-id=${MYSQL_SLAVE_1_SERVER_ID}",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      "--default_authentication_plugin=mysql_native_password",
      "--read-only=1",
    ]
    networks:
      web:
        ipv4_address: ${NETWORK_MYSQL_SLAVE_1}

  pgsql-master: &pgsql-master
    restart: always
    build: ./images/pgsql
    container_name: pgsql-master
    hostname: pgsql-master
    privileged: true
    user: root
    environment:
      TZ: Asia/Shanghai
      POSTGRES_USER: ${PGSQL_MASTER_USER}
      POSTGRES_PASSWORD: ${PGSQL_MASTER_PWD}
    ports:
      - ${PORT_PGSQL_MASTER}:5432
    volumes:
      - postgres_master_data:/var/lib/postgresql/data
      # - ./etc/pgsql/master/data:/var/lib/postgresql/data
    networks:
      web:
        ipv4_address: ${NETWORK_PGSQL_MASTER}

  pgadmin4:
    restart: always
    build: ./images/pgadmin4
    container_name: pgadmin4
    hostname: pgadmin4
    environment:
      TZ: Asia/Shanghai
      PGADMIN_DEFAULT_EMAIL: hunzsig
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - ${PORT_PGSQL_ADMIN4}:80
    networks:
      web:
        ipv4_address: ${NETWORK_PGSQL_ADMIN4}

  mongo-rs-1: &mongo-rs-1
    restart: always
    build: ./images/mongo
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_RS_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_RS_PWD}
    ports:
      - ${PORT_MONGO_RS_1}:27017
    volumes:
      - mongo_rs1_data:/data/db
      - ./etc/mongo/rs1/mongo.conf:/etc/mongo.conf
      - ./etc/mongo/rs1/log:/var/log/mongodb
    command: [
      "--replSet=rs",
      "--keyFile=/data/mongodb.key",
    ]
    networks:
      web:
        ipv4_address: ${NETWORK_MONGO_RS_1}

  mongo-rs-2: &mongo-rs-2
    <<: *mongo-rs-1
    restart: always
    build: ./images/mongo
    depends_on:
      - mongo-rs-1
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_RS_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_RS_PWD}
    ports:
      - ${PORT_MONGO_RS_2}:27017
    volumes:
      - mongo_rs2_data:/data/db
      - ./etc/mongo/rs2/mongo.conf:/etc/mongo.conf
      - ./etc/mongo/rs2/log:/log
    command: [
      "--replSet=rs",
      "--keyFile=/data/mongodb.key",
    ]
    networks:
      web:
        ipv4_address: ${NETWORK_MONGO_RS_2}

  mongo-rs-3: &mongo-rs-3
    <<: *mongo-rs-1
    restart: always
    build: ./images/mongo
    depends_on:
      - mongo-rs-1
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_RS_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_RS_PWD}
    ports:
      - ${PORT_MONGO_RS_3}:27017
    volumes:
      - mongo_rs3_data:/data/db
      - ./etc/mongo/rs3/mongo.conf:/etc/mongo.conf
      - ./etc/mongo/rs3/log:/log
    command: [
      "--replSet=rs",
      "--keyFile=/data/mongodb.key",
    ]
    networks:
      web:
        ipv4_address: ${NETWORK_MONGO_RS_3}



volumes:
  postgres_master_data:
  mongo_rs1_data:
  mongo_rs2_data:
  mongo_rs3_data:
