version: "2.0"

services:

  php:
    image: php:5.6-fpm
    volumes:
      - .:/app
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    hostname: nginx
    ports:
      - 90:80
      - 443:443
    volumes:
      - /Volumes/hunzsig-apfs/Web/workSpace/hunzsigGithub/docker/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /Volumes/hunzsig-apfs/Web/workSpace/hunzsigGithub/docker/log/nginx:/var/log/nginx
      - /Volumes/hunzsig-apfs/Web/workSpace/hunzsigGithub/docker/www:/var/www
  redis:
    restart: always
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - /Volumes/hunzsig-apfs/Web/workSpace/hunzsigGithub/docker/etc/mysql/data:/var/lib/mysql
  pgsql:
    image: postgres:10.10
    container_name: pgsql
    hostname: pgsql
    ports:
      - 5432:5432
    volumes:
      - /Volumes/hunzsig-apfs/Web/workSpace/hunzsigGithub/docker/etc/pgsql/data:/var/lib/postgresql/data