version: "2.0"

services:

  php-5.6:
    restart: always
    image: php:5.6-fpm
    container_name: php-5.6
    hostname: php-5.6
    ports:
      - 9056:9056
    volumes:
      - .:/app
#  php-7.0:
#    restart: always
#    image: php:7.0-fpm
#    container_name: php-7.0
#    hostname: php-7.0
#    ports:
#      - 9070:9000
#    volumes:
#      - .:/app
#  php-7.1:
#    restart: always
#    image: php:7.1-fpm
#    container_name: php-7.1
#    hostname: php-7.1
#    ports:
#      - 9071:9000
#    volumes:
#      - .:/app
#  php-7.2:
#    restart: always
#    image: php:7.2-fpm
#    container_name: php-7.2
#    hostname: php-7.2
#    ports:
#      - 9072:9000
#    volumes:
#      - .:/app
  php-7.3:
    restart: always
    image: php:7.3-fpm
    container_name: php-7.3
    hostname: php-7.3
    ports:
      - 9073:9000
    volumes:
      - .:/app
      - ${WORD_PWD}/www:/var/www


  nginx:
    restart: always
    image: nginx
    container_name: nginx
    hostname: nginx
    ports:
      - 8080:80
      - 2002:2002
      - 19001:19001
    depends_on:
      - php-5.6
      - php-7.3
    volumes:
      - ${WORD_PWD}/etc/nginx:/etc/nginx
      - ${WORD_PWD}/log/nginx:/var/log/nginx
      - ${WORD_PWD}/www:/var/www


  mysql-master:
    restart: always
    image: mysql:8.0
    container_name: mysql-master
    hostname: mysql-master
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=${MYSQL_MASTER_ROOT_PWD}
    ports:
      - ${MYSQL_MASTER_PORT}:3306
    expose:
      - ${MYSQL_MASTER_PORT}
    volumes:
      - ${WORD_PWD}/etc/mysql/master/data:/var/lib/mysql
    command: [
      "--log-bin=mysql-bin",
      "--server-id=${MYSQL_MASTER_SERVER_ID}",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      "--innodb_flush_log_at_trx_commit=1",
      "--sync_binlog=1"
    ]
  mysql-slave-1:
    restart: always
    image: mysql:8.0
    container_name: mysql-slave-1
    hostname: mysql-slave-1
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=${MYSQL_SLAVE_1_ROOT_PWD}
      - MASTER_MYSQL_ROOT_PASSWORD=${MYSQL_MASTER_ROOT_PWD}
    ports:
      - ${MYSQL_SLAVE_1_PORT}:3306
    depends_on:
      - mysql-master
    volumes:
      - ${WORD_PWD}/etc/mysql/slave_1/data:/var/lib/mysql
    command: [
      "--server-id=${MYSQL_SLAVE_1_SERVER_ID}",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
    ]


  pgsql:
    restart: always
    image: postgres:10.10
    container_name: pgsql
    hostname: pgsql
    ports:
      - ${PGSQL_PORT}:5432
    volumes:
      - ${WORD_PWD}/etc/pgsql/data:/var/lib/postgresql/data


  redis:
    restart: always
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - ${REDIS_PORT}:6379
